CREATE TABLE vehicles (
    id CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(150) NOT NULL,
    fipe_code VARCHAR(15) NOT NULL,
    price DECIMAL(18, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  NOT NULL
);
